pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y install libatasmart-dev
      - autoreconf -fis
      - ./configure
      - make -j8

  unittests:
    image: library/debian:unstable
    commands:
      - make check
