pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y upgrade
      - apt-get -y install devscripts
      - pwd && ls
      - mk-build-deps --install debian/control
      - autoreconf -fis
      - ./configure
      - make -j8

  unittests:
    image: library/debian:unstable
    commands:
      - make check
