pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts pciutils
      - mk-build-deps --install debian/control
      - dpkg-checkbuilddeps
      - autoreconf -fis
      - ./configure
      - make -j8

  unittests:
    image: library/debian:unstable
    commands:
      - make check
