pipeline:
  build:
    image: library/debian:unstable
    commands: 
      - apt-get update
      - apt-get -y dist-upgrade
      - apt-get -y install devscripts pciutils
      - mk-build-deps --install -t'apt-get -y install'
      - dpkg-checkbuilddeps
      - autoreconf -fis
      - ./configure
      - make -j8

        #- apt-get -y install libatasmart-dev libblkid-dev libcryptsetup-dev libpci-dev libpciaccess-dev libdevmapper-dev libudev-dev
  unittests:
    image: library/debian:unstable
    commands:
      - make check
